# Generated by Django 3.2.9 on 2021-11-30 19:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignmentName', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userID', models.CharField(max_length=20)),
                ('userName', models.CharField(max_length=20)),
                ('userContact', models.IntegerField()),
                ('userSSN', models.IntegerField()),
                ('userAddress', models.CharField(max_length=20)),
                ('userPassword', models.CharField(max_length=20)),
                ('userType', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Lab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('labName', models.CharField(max_length=20)),
                ('labDays', models.CharField(max_length=20)),
                ('labHours', models.CharField(max_length=20)),
                ('labLocation', models.CharField(max_length=20)),
                ('labTA', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='TAScheduler.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseName', models.CharField(max_length=20)),
                ('courseTime', models.CharField(max_length=20)),
                ('courseDays', models.CharField(max_length=20)),
                ('courseHours', models.CharField(max_length=20)),
                ('courseInstructor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='TAScheduler.userprofile')),
                ('courseTA', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='USERPROFILE_set', to='TAScheduler.userprofile')),
            ],
        ),
    ]
