# Generated by Django 3.2.9 on 2021-12-07 20:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseID', models.IntegerField()),
                ('name', models.CharField(max_length=20)),
                ('location', models.CharField(max_length=20)),
                ('hours', models.TimeField()),
                ('days', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Lab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('labID', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=20)),
                ('location', models.CharField(max_length=20)),
                ('hours', models.CharField(max_length=20)),
                ('days', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userID', models.IntegerField(default=0)),
                ('userType', models.CharField(max_length=20)),
                ('userPassword', models.CharField(max_length=20)),
                ('userName', models.CharField(max_length=20)),
                ('userAddress', models.CharField(max_length=20)),
                ('userContact', models.IntegerField(default=0)),
                ('userEmail', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courses', models.ManyToManyField(to='TAScheduler.Course')),
                ('labs', models.ManyToManyField(to='TAScheduler.Lab')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TAScheduler.userprofile')),
            ],
        ),
        migrations.AddField(
            model_name='lab',
            name='TA',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='TAToLab', to='TAScheduler.userprofile'),
        ),
        migrations.AddField(
            model_name='lab',
            name='instructor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='TAScheduler.userprofile'),
        ),
        migrations.AddField(
            model_name='course',
            name='TAs',
            field=models.ManyToManyField(related_name='TAToCourse', to='TAScheduler.UserProfile'),
        ),
        migrations.AddField(
            model_name='course',
            name='instructor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='TAScheduler.userprofile'),
        ),
        migrations.AddField(
            model_name='course',
            name='labs',
            field=models.ManyToManyField(to='TAScheduler.Lab'),
        ),
    ]
